/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CMS": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "FileStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyDatabase": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "Site": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
